GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{  
    
  "title": "mi titulo",
  "author": "mi author",
  "url": "mi url",
  "likes": 100

}
